-- $Id: sena.sql,v 1.2 2004/05/09 23:29:32 mmr Exp $
DROP TABLE sena;
CREATE TABLE sena (
  id SERIAL NOT NULL PRIMARY KEY,
  d1 INT NOT NULL,
  d2 INT NOT NULL,
  d3 INT NOT NULL,
  d4 INT NOT NULL,
  d5 INT NOT NULL,
  d6 INT NOT NULL,
  data DATE NOT NULL UNIQUE
);

CREATE FUNCTION 
